# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMUnitStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=3, unique=True, verbose_name='UID')),
                ('status', models.CharField(max_length=3, verbose_name='Status')),
                ('sett', models.CharField(max_length=3, verbose_name='Set Temperature')),
                ('roomt', models.CharField(max_length=6, verbose_name='Room Temperature')),
                ('fanspeed', models.CharField(max_length=4, verbose_name='Fan Speed')),
                ('opmode', models.CharField(max_length=4, verbose_name='Operation Mode')),
                ('ecode', models.CharField(max_length=4, verbose_name='Failure Code')),
            ],
        ),
    ]
